name = "Hardcore Vanilla+"
author = "charley"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "027bf0b5391a022e47b39879dd2f337750e1580d7f4a0aa324714af368feeb12"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
