name = "Hardcore Vanilla+"
author = "charley"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f441f0457dda5506608f929a9d3c8bac01292c0910c40376199afbaadb3449b7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
