name = "Hardcore Vanilla+"
author = "charley"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0718fbba8715375633cf11c65399c168d730bcd4f7f9c4926630dd4928f24690"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
