name = "Hardcore Vanilla+"
author = "charley"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14b9dc985a65f18022fedf5207b4633f0ada3c142d5ebac25255cbf51e1ebb59"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
