name = "Hardcore Vanilla+"
author = "charley"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce7e889447969510465f9a765090542637a2c9d45a8a0a154997b2484aa48200"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
